_wandb:
    value:
        cli_version: 0.21.3
        e:
            t3eh85ixzc7nh00x3epjrk1joj4gjb66:
                args:
                    - --input_artifact
                    - preprocessed_data.csv:latest
                    - --artifact_root
                    - /home/patricia_walker/genre_classification
                    - --artifact_type
                    - segregated_data
                    - --test_size
                    - "0.3"
                    - --random_state
                    - "42"
                    - --stratify
                    - genre
                codePath: segregate/run.py
                codePathLocal: run.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "33486176256"
                email: pwal192@wgu.edu
                executable: /home/patricia_walker/miniconda3/envs/mlflow-2b05c334639a6588d5c96ec48ecc7de59f6ca254/bin/python
                git:
                    commit: 2b4f36393b9238dda534595bbe8e495ba7abb79e
                    remote: https://github.com/Silent-Walker423/genre_classification.git
                gpu: NVIDIA GeForce RTX 2070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2070
                      uuid: GPU-f51412e9-e663-add3-39ec-a714a6321893
                host: Silent-Walker-PC
                memory:
                    total: "33565134848"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/patricia_walker/genre_classification/segregate/run.py
                python: CPython 3.13.9
                root: /home/patricia_walker/genre_classification/segregate
                startedAt: "2025-11-17T13:23:08.843310Z"
                writerId: t3eh85ixzc7nh00x3epjrk1joj4gjb66
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "4": 3.13.9
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
