_wandb:
    value:
        cli_version: 0.21.3
        e:
            5r9dgddpp0g1swl9wqugo8o90ujbkfti:
                args:
                    - --file_url
                    - https://github.com/udacity/nd0821-c2-build-model-workflow-exercises/blob/master/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/genres_mod.parquet?raw=true
                    - --artifact_name
                    - raw_data.parquet
                    - --artifact_type
                    - raw_data
                    - --artifact_description
                    - Data as downloaded
                codePath: download/download_data.py
                codePathLocal: download_data.py
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "33895120896"
                email: pwal192@wgu.edu
                executable: /home/patricia_walker/miniconda3/envs/mlflow-c8796fcdf2a60e9d2d7a0e2de87ce7cf78fe7920/bin/python
                git:
                    commit: 33e50caff491f3a58286932a56c9f5fc0ce3fe95
                    remote: https://github.com/Silent-Walker423/genre_classification.git
                gpu: NVIDIA GeForce RTX 2070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2070
                      uuid: GPU-f51412e9-e663-add3-39ec-a714a6321893
                host: Silent-Walker-PC
                memory:
                    total: "33565134848"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/patricia_walker/genre_classification/download/download_data.py
                python: CPython 3.13.9
                root: /home/patricia_walker/genre_classification/download
                startedAt: "2025-11-17T15:32:02.385450Z"
                writerId: 5r9dgddpp0g1swl9wqugo8o90ujbkfti
        m: []
        python_version: 3.13.9
        t:
            "3":
                - 2
            "4": 3.13.9
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
