_wandb:
    value:
        cli_version: 0.21.3
        e:
            unftdhqtva8z8ixuxvl1gkaonbwrvuep:
                args:
                    - -s
                    - -vv
                    - .
                    - --reference_artifact
                    - exercise_14/preprocessed_data.csv:latest
                    - --sample_artifact
                    - preprocessed_data.csv:latest
                    - --ks_alpha
                    - "0.05"
                cpu_count: 8
                cpu_count_logical: 8
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "33895411712"
                email: pwal192@wgu.edu
                executable: /home/patricia_walker/miniconda3/envs/mlflow-8b8c5bbbcf30a4f621fb194c7af489e467ffbbf1/bin/python3.13
                git:
                    commit: 33e50caff491f3a58286932a56c9f5fc0ce3fe95
                    remote: https://github.com/Silent-Walker423/genre_classification.git
                gpu: NVIDIA GeForce RTX 2070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 2070
                      uuid: GPU-f51412e9-e663-add3-39ec-a714a6321893
                host: Silent-Walker-PC
                memory:
                    total: "33565134848"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/patricia_walker/miniconda3/envs/mlflow-8b8c5bbbcf30a4f621fb194c7af489e467ffbbf1/bin/pytest
                python: CPython 3.13.9
                root: /home/patricia_walker/genre_classification/check_data
                startedAt: "2025-11-17T15:32:23.268054Z"
                writerId: unftdhqtva8z8ixuxvl1gkaonbwrvuep
        m: []
        python_version: 3.13.9
        t:
            "4": 3.13.9
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
